title:            Rinat Enikeev
description:      "Full stack"
logo:             logo.png
disqus_shortname: rinat-enikeev
share:            true
dropcap:	      true
url:        	  http://rinat-enikeev.github.io #http://localhost:4000

# Owner/author information
owner:
  name:           Rinat Enikeev
  avatar:         avatar.png
  email:          rinat.enikeev@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Yet another software developer
  # Social networking links used in footer. Update and remove as you like.
  twitter:        rinat_enikeev
  facebook:       enikeev
  github:         rinat-enikeev
  instagram:
# stackoverflow: users/840742/renatus
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/101507731270027025544

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-66551812-1
google_verify:
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: CV
    url: /cv
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Yekaterinburg
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://rinat-enikeev.github.io'
  relativeLinks: 'http://rinat-enikeev.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

#Resume
author:
  name: Rinat Enikeev
  title: iOS Developer
  address: Ufa, Russia
  email: rinat.enikeev@gmail.com
  github: rinat-enikeev
  skype: rinatenikeev
  facebook: enikeev
  workHistory:
    - work1:
      company: Independent & Contract iOS Development
      location: Ufa, Russia
      title: iOS Developer
      started: 2014
      duration: (2014 - Present)
      description:
    - work2:
      company: it.ru
      location: Ufa, Russia
      title: Senior Java Developer
      started: 2012
      duration: (2012 - 2014)
      description:
    - work3:
      company: The Institute of Radioengineering and Electronics of Russian Academy of Sciences
      location: Moscow, Russia
      title: Junior Researcher
      started: 2010
      duration: (2010 - 2011)
      description:
    - work4:
      company: Mail.ru
      location: Moscow, Russia
      title: Software Developer
      started: 2009
      duration: (2009 - 2010)
      description:
    - work4:
      company: OGK2
      location: Moscow, Russia
      title: Software Developer
      started: 2008
      duration: (2008 - 2009)
      description:
    - work5:
      company: Big Soil
      location: Moscow, Russia
      title: Software Developer
      started: 2007
      duration: (2007 - 2008)
      description:
    - work5:
      company: Lamira
      location: Moscow, Russia
      title: Software Developer
      started: 2006
      duration: (2006 - 2007)
      description:
  educationHistory:
    - education1:
      organization: USATU
      degree: Bachelor
      major: Computer Science
      started: 2012
      duration: (2012 - 2016)
      description:
    - education2:
      organization: Mephi
      degree: Master
      major: Materials science
      started: 2004
      duration: (2004 - 2010)
      description:
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Russian
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Objective C
      percentage: 100%
    - skill2:
      name: Swift
      percentage: 100%
    - skill3:
      name: Cocoa Touch
      percentage: 90%
    - skill4:
      name: Java/Java EE
      percentage: 90%
    - skill5:
      name: Git
      percentage: 90%
    - skill6:
      name: HTTP/Rest
      percentage: 80%